
<a href="https://npmjs.org/packages/wedgetail" rel="nofollow">
  <img alt="View on npm" src="https://img.shields.io/npm/v/wedgetail.svg" style="max-width:100%;">
</a>
&nbsp;
<a href="https://npmjs.org/packages/wedgetail" rel="nofollow">
  <img alt="npm downloads" src="https://img.shields.io/npm/dm/wedgetail.svg" style="max-width:100%;">
</a>

<br />
<br />

<a href="https://david-dm.org/ojkelly/wedgetail" rel="nofollow">
  <img alt="Dependencies" src="https://img.shields.io/david/ojkelly/wedgetail.svg" style="max-width:100%;">
</a>
&nbsp;
<a href="https://travis-ci.org/ojkelly/wedgetail" rel="nofollow">
  <img alt="Build Status" src="https://travis-ci.org/ojkelly/wedgetail.svg?branch=master" style="max-width:100%;">
</a>
&nbsp;
<a href="https://codecov.io/gh/ojkelly/wedgetail" rel="nofollow">
  <img alt="codecov" src="https://codecov.io/gh/ojkelly/wedgetail/branch/master/graph/badge.svg" style="max-width:100%;">
</a>
&nbsp;
<a href="https://nodesecurity.io/orgs/ojkelly/projects/7f441bdb-76ab-4155-aec9-00777b5adc9a" rel="nofollow">
  <img alt="NSP Status" src="https://nodesecurity.io/orgs/ojkelly/projects/7f441bdb-76ab-4155-aec9-00777b5adc9a/badge" style="max-width:100%;">
</a>
