<a class="github-button" href="https://github.com/ojkelly/wedgetail" data-icon="octicon-star" data-show-count="true" aria-label="Star ojkelly/wedgetail on GitHub">Star</a>
<!-- GitHub fork -->
&nbsp;
<a class="github-button" href="https://github.com/ojkelly/wedgetail/fork" data-icon="octicon-repo-forked" data-show-count="true" aria-label="Fork ojkelly/wedgetail on GitHub">Fork</a>
<!-- Github Button -->
&nbsp;
<a href="https://npmjs.org/packages/wedgetail" rel="nofollow">
  <img alt="npm downloads" src="https://img.shields.io/npm/dm/wedgetail.svg" style="max-width:100%;">
</a>
<script async defer src="https://buttons.github.io/buttons.js"></script>
