<a class="github-button" href="https://github.com/ojkelly/wedgetail" data-icon="octicon-star" data-show-count="true" aria-label="Star ojkelly/wedgetail on GitHub">Star</a>
<!-- GitHub fork -->
<a class="github-button" href="https://github.com/ojkelly/wedgetail/fork" data-icon="octicon-repo-forked" data-show-count="true" aria-label="Fork ojkelly/wedgetail on GitHub">Fork</a>
<!-- Github Button -->
<script async defer src="https://buttons.github.io/buttons.js"></script>
