<a href="https://npmjs.org/packages/wedgetail" rel="nofollow"><img alt="View on npm" src="https://img.shields.io/npm/v/wedgetail.svg" style="max-width:100%;"></a>
&nbsp;
<a href="https://npmjs.org/packages/wedgetail" rel="nofollow"><img alt="npm downloads" src="https://img.shields.io/npm/dm/wedgetail.svg" style="max-width:100%;"></a>
&nbsp;
<a href="https://travis-ci.org/ojkelly/wedgetail" rel="nofollow"><img alt="Build Status" src="https://travis-ci.org/ojkelly/wedgetail.svg?branch=master" style="max-width:100%;"></a>

&nbsp;
<a class="github-button" href="https://github.com/ojkelly/wedgetail" data-icon="octicon-star" data-show-count="true" aria-label="Star ojkelly/wedgetail on GitHub">Star</a>
<script async defer src="https://buttons.github.io/buttons.js"></script>
